### ISSUE TITLE
about  “csi2_hamming_dec.v”  error corrected flag

### ISSUE THREAD

**Issue by cumtdaibo** [hellgate202/csi2#1]
@hellgate202 
 at line 140: 
  if( err_bit_pos != 5'hf )   
            error_corrected_o <= 1'b1;  

I think the judging condition is: if( err_bit_pos != **5'h1f** ) , meaning that there are 2 or more bit error.
It may be a mistake in writing.

**Comment by hellgate202** [comment]
Hamming correction codes provide one bit error correction and two bit error detection. If err_bit_pos is equal to 5'hf, then more than one error was detected. If it is equal to some other value - there was one bit error and it can be corrected. If there more than 2 bit errors we can't do anything and hamming code corrector won't work here. So it's possible to have err_bit_pos equal to something else than 5'h1f in case of 2,3,4.., bit errors. For now I'm just ignoring it.

**Comment by cumtdaibo** [comment]
Sorry for my mistaken question.
From your code, the  '**err_bit_pos**' result from looking syndrome up from a rom table, the rom table contain 64 values, 0x00~0x17, corresponding to 24 single bit error position, the else 40 values are all 0x1F, meaning that 2 or more errors occured, and can not be corrected.   
So I think the '**error_corrected_o**'  is set high when '**err_bit_pos**' is not 0x1F.  And 0x0F is just mean the single error position is 15.
Thank you! @hellgate202
